/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header$
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define yywrap() 1
#define YY_SKIP_YYWRAP
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 44
#define YY_END_OF_BUFFER 45
static yyconst short int yy_accept[376] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,   45,   42,
       42,   43,    1,   42,    1,   42,   42,   42,   42,   42,
       42,   42,   42,   42,   42,   42,   42,   42,   42,   42,
       42,   42,   42,   42,   42,   42,   42,   42,   42,   42,
       42,   42,   42,   42,   42,    0,    1,    1,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    1,
        2,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,   19,    0,    0,    0,
        0,   28,    0,   27,    0,   26,    0,   21,    0,   25,
        0,   24,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,   14,    0,    0,    0,    0,    0,
        0,   36,    0,    0,   39,    0,    0,    0,   22,   23,
        0,    0,    0,    0,    0,    0,    0,   20,    0,    0,
        0,   20,    0,    0,    0,    0,    0,   20,    0,    0,
        0,    0,    0,    0,    0,    0,    4,    3,    5,    0,

        0,    0,    0,    0,    0,    0,    0,   34,   35,   37,
       38,   19,    0,    0,    0,    0,    0,    0,    0,    0,
       20,   20,    0,    0,    0,    0,    0,    0,    6,    0,
        0,    5,    5,    0,    0,    0,   29,    0,   32,    0,
        0,    0,    0,    0,    0,   20,   20,    0,    0,    0,
       20,   20,    0,    0,    0,    0,    0,   13,    0,    0,
        0,    5,    5,    0,    0,   30,    0,   33,    0,   40,
       41,    0,    0,   20,   20,   40,   41,    0,    0,    0,
        0,    6,    0,    0,    0,    0,    0,    0,    0,   20,
       20,    0,    0,    0,    0,    0,   15,   16,    7,    0,

        0,    0,   40,   41,    0,    0,    0,    0,   12,   11,
        0,   31,    0,    0,    0,    0,    0,    7,    6,    6,
        6,    6,    0,    6,    6,    6,    0,    0,   10,    0,
       10,    6,    6,    6,    0,    0,    0,    0,    0,    6,
        6,    6,    0,    0,    0,   10,    9,    6,    6,    6,
        0,    0,   20,    0,    6,    6,    6,    0,    0,   10,
        0,    6,    6,    6,    6,   18,    0,    8,    0,    0,
        0,    0,    8,   17,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    5,    1,    6,    7,    1,    1,    1,    1,    1,
        1,    1,    8,    9,   10,    1,    1,   11,   12,   13,
       11,   11,   11,   11,   11,   11,   11,   14,    1,    1,
       15,    1,    1,    1,   16,   17,   18,   19,   17,   17,
       17,   17,   17,   17,   17,   17,   20,   17,   17,   21,
       17,   17,   17,   17,   17,   22,   17,   23,   17,   17,
       24,    1,   25,    1,    1,    1,   26,   27,   28,   29,

       30,   31,   32,   33,   34,    1,   35,   36,   37,   38,
       39,   40,    1,   41,   42,   43,   44,   45,    1,   46,
       47,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[48] =
    {   0,
        1,    2,    3,    4,    1,    5,    4,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1
    } ;

static yyconst short int yy_base[402] =
    {   0,
        0,    6,   47,   29,   40,   51,   56,   72,  804, 1303,
       39, 1303,    0,  114,  797,   98,  141,   23,  103,    1,
      768,   28,  753,  757,   57,  182,  747,  753,  737,  732,
      724,  153,  122,  164,  727,  722,  731,  137,   30,  196,
      717,  707,  707,  197,   42,   99,    0,    0,    0,  232,
        0,  131,  195,   78,  706,  113,  691,  695,  147,  719,
     1303,  209,  217,   55,  170,  244,  248,  260,  264,  276,
      280,  249,  265,  233,  281,  680,  685,  675,  669,  661,
      662,  188,  658,  292,  642,    0,  646,  646,  632,  612,
      608,  611,  614,  598,  599,  596,    0,  271,  298,  592,

      590,  597,  572,  573,  571,    0,   55,  299,  566,  558,
      565,  542,  534,  538,    0,   84,  306,    0,  314,  334,
      338,  139,  350,  217,  354,  309,  366,  319,  370,  373,
      385,  380,  355,  397,  402,  415,  417,  423,  424,  403,
      431,  439,  447,  445,  459,  520,  524,  521,  211,  518,
      519,  464,  313,  465, 1303,  507,  476,  494,  503,  497,
      495, 1303,  487,  488, 1303,  458,  458,  487,  471,  477,
      490,  494,  507,  495,  521,  523,  537,  539,  545,  552,
      563,  569,  538,  447,  446,  577,  581,  509,  511,    0,
      593,  443,  440,  371,  579,  421, 1303,  588,  608,    0,

      434,  601,  620,  613,  622,  402,  402, 1303, 1303, 1303,
     1303, 1303,  633,  634,  648,  654,  640,  433,  660,  667,
      673,  675,  398,  391,  680,  405,  380,  685,  686,    0,
      175,  706,  718,  395,  365,  723,  689,  701, 1303,  735,
      736,  737,  362,  749,  751,  451, 1303,  757,    0,   89,
      765,  767,  342,  349,  772,  359,  340,  780,  358,  315,
      302,  732,  800,  398,  805,  767,  793, 1303,  817,  818,
      819,   69,  156,  824,  833, 1303, 1303,  835,  318,  309,
      430, 1303,  416,  341,  840,  846,  850,    4,  179,  851,
      857,  864,  290,  318,  253,  872, 1303, 1303,  862,    0,

      884,  869,  311,  307,  886,  281,  286,  264, 1303,  885,
      268,  891,  903,  908,  235,  226,  910, 1303,  919,  925,
      927,  932,  952,  963,  975,  977,  206,  188,  934,    0,
      991,  983,  989,  996, 1002, 1018, 1032, 1038, 1024, 1050,
     1062, 1064,  170,  169,  171, 1040, 1052, 1076, 1078, 1084,
     1090, 1103, 1120, 1126,    0, 1132, 1134,  145,  135, 1303,
     1085, 1105, 1140, 1146, 1148, 1303,  130, 1154,    0,   72,
       73,   40, 1303, 1303, 1303, 1179, 1184, 1189, 1194, 1199,
     1204, 1209, 1214, 1218, 1223, 1228, 1233, 1238, 1242, 1247,
     1251, 1255, 1260, 1264, 1269, 1274, 1279, 1284, 1288, 1293,

     1298
    } ;

static yyconst short int yy_def[402] =
    {   0,
      376,  376,  376,    2,  376,    2,  376,    2,  375,  375,
      375,  375,  377,  375,  378,  375,  375,  379,  379,  375,
      375,  375,  375,  375,  375,  375,  375,  375,  375,  375,
      375,   14,  375,  375,  375,  375,  375,   14,  375,  375,
      375,  375,  375,   14,  375,  375,  377,  377,   14,  375,
       17,  379,  379,  375,  375,  375,  375,  375,  375,  378,
      375,  380,  380,  375,  375,  375,  375,  375,  375,  375,
      375,  379,  381,  382,  379,  375,  375,  375,  375,  375,
      375,  375,  375,  375,  375,   26,  375,  375,  375,  375,
      375,  375,  375,  375,  375,  375,   32,  375,  375,  375,

      375,  375,  375,  375,  375,   38,  375,  375,  375,  375,
      375,  375,  375,  375,   44,  375,  380,  383,  375,  375,
      375,  375,  375,  375,  375,  375,  375,  375,  375,  375,
      375,  375,  375,  379,  381,  382,  384,  375,  381,  375,
      375,  382,  375,  385,  379,  375,  375,  375,  375,  375,
      375,  375,  375,  386,  375,  375,  375,  375,  375,  375,
      375,  375,  375,  375,  375,  375,  375,  383,  375,  375,
      375,  381,  381,  375,  382,  382,  382,  384,  385,  384,
      387,  385,  375,  375,  375,  375,  375,  385,  385,  388,
      379,  375,  375,  375,  389,  375,  375,  375,  386,  390,

      375,  375,  375,  375,  375,  375,  375,  375,  375,  375,
      375,  375,  381,  382,  382,  387,  388,  388,  387,  388,
      385,  385,  375,  375,  379,  375,  375,  375,  389,  391,
      375,  375,  386,  390,  375,  375,  375,  375,  375,  375,
      375,  375,  375,  382,  382,  381,  375,  388,  388,  388,
      385,  385,  375,  375,  379,  375,  375,  375,  391,  375,
      375,  375,  375,  375,  375,  375,  375,  375,  375,  382,
      382,  388,  388,  385,  385,  375,  375,  379,  375,  375,
      375,  375,  375,  375,  392,  375,  375,  388,  388,  385,
      385,  379,  375,  375,  375,  375,  375,  375,  392,  393,

      375,  375,  388,  388,  382,  375,  375,  375,  375,  375,
      393,  375,  389,  394,  375,  375,  395,  375,  396,  389,
      389,  394,  397,  389,  394,  394,  375,  375,  395,  398,
      395,  396,  389,  389,  397,  391,  397,  391,  399,  389,
      394,  394,  375,  375,  398,  395,  395,  389,  389,  382,
      391,  391,  399,  399,  388,  394,  394,  375,  375,  375,
      400,  389,  389,  394,  394,  375,  375,  400,  401,  375,
      401,  375,  375,  375,    0,  375,  375,  375,  375,  375,
      375,  375,  375,  375,  375,  375,  375,  375,  375,  375,
      375,  375,  375,  375,  375,  375,  375,  375,  375,  375,

      375
    } ;

static yyconst short int yy_nxt[1351] =
    {   0,
      375,   11,   12,  375,   11,  247,   13,   14,   12,  247,
       14,  375,   15,  375,   16,   17,   16,   16,   16,   76,
       77,   18,   18,   18,   18,   18,   19,   18,   18,   20,
       32,   73,   21,   32,   22,   23,   74,   73,  272,   24,
       46,   34,   12,   46,   34,   47,   13,   25,   26,   12,
      303,   26,   38,   13,   27,   38,  119,   40,   12,  119,
       40,   79,   13,   28,  374,   81,   29,  103,   80,   35,
       33,   31,   27,   44,  247,   36,   44,   81,  373,  112,
       39,   28,   37,   83,   29,   41,   36,   84,   30,   31,
       81,   42,  103,   37,  247,   85,   76,   77,   43,   62,

       46,   45,   62,   46,  288,   47,   50,   42,   50,   50,
       50,   73,   63,  372,   43,   49,   74,   73,   49,   81,
       47,  112,   50,   51,   50,   50,   50,  273,   75,   52,
       52,   52,   52,   52,   53,   52,   52,   54,  106,   73,
       55,  106,   56,   57,   74,   73,   79,   58,   83,  122,
      122,  122,   84,   80,   97,   59,   64,   97,   65,  370,
       85,  247,   66,   67,   95,   99,  107,  367,   99,  366,
       47,  120,  101,   83,  120,   68,  360,   84,   87,  102,
       69,   70,   71,   86,  247,   85,   86,   88,   47,  152,
       89,  289,  152,  100,   98,   91,  359,  108,  115,  101,

      108,  115,   47,   73,  260,  261,  102,   87,   74,   73,
       62,  358,  195,   62,  118,  195,   88,  304,  375,   89,
       75,  375,  118,   90,   91,  109,  116,  124,  124,  124,
      344,  110,  110,   62,  141,  343,   62,  142,  111,  111,
       50,  143,   50,   50,   50,  121,   63,  144,  121,  123,
      133,  328,  123,  134,  122,  122,  122,  135,  124,  124,
      124,  125,  136,  137,  125,  127,  138,  327,  127,  139,
      126,  126,  126,  318,  128,  128,  128,  129,  140,  308,
      129,  131,  133,  309,  131,  134,  130,  130,  130,  135,
      132,  132,  132,  154,  136,  137,  154,   83,  309,   99,

      108,   84,   99,  108,   47,   47,  316,  375,  315,   85,
      375,  375,  247,   95,  154,  119,  247,  154,  119,  126,
      126,  126,  307,  145,  169,  169,  169,  100,  109,  128,
      128,  128,  306,  101,  110,  120,  294,  155,  120,  121,
      102,  111,  121,  293,  170,  170,  170,  284,  122,  122,
      122,  123,  297,  298,  123,  125,  133,  283,  125,  133,
      124,  124,  124,  282,  126,  126,  126,  127,  140,  144,
      127,  129,  228,  280,  129,  228,  128,  128,  128,  279,
      130,  130,  130,  130,  130,  130,  131,  277,  276,  131,
      132,  132,  132,  269,  264,  132,  132,  132,  133,  285,

      263,  134,  285,  171,  183,  135,  172,  183,  257,  256,
      136,  137,  173,  173,  173,  140,  174,  296,  179,  175,
      296,  180,  181,  143,  138,  138,  254,  138,  139,  144,
      182,  281,  141,  253,  281,  141,  140,  140,  247,  243,
      141,  242,  184,  142,  185,  144,  189,  143,  186,  189,
      190,  186,  138,  144,  176,  139,  177,  187,  187,  187,
      133,  235,  231,  134,  140,  152,  154,  135,  152,  154,
      200,  295,  136,  137,  198,  198,  198,  202,  227,  226,
      202,  169,  169,  169,  224,  223,  191,  170,  170,  170,
      203,  171,  212,  211,  171,  171,  174,  210,  172,  174,

      187,  187,  187,  140,  173,  173,  173,  140,  133,  144,
      375,  213,  189,  375,  375,  189,  190,  173,  173,  173,
      140,  137,  174,  209,  141,  175,  208,  142,  207,  143,
      206,  143,  205,  204,  184,  144,  185,  144,  141,  183,
      138,  142,  183,  139,   73,  143,  179,  201,  197,  179,
      190,  144,  182,  179,  196,  194,  180,  181,  182,  193,
      176,  214,  177,  192,  217,  182,  218,  219,   73,  218,
      183,  167,  166,  183,  375,  215,  220,  184,  186,  185,
      195,  186,  141,  195,  230,  141,  165,  187,  187,  187,
      114,  187,  187,  187,  133,  144,  113,  134,  198,  198,

      198,  135,  202,  112,  164,  202,  136,  137,  221,  232,
      222,  163,  232,  375,  238,  203,  162,  238,  233,  233,
      233,  236,  105,  240,  236,  225,  240,  239,  104,  103,
      237,  237,  237,  161,  133,  141,  241,  213,  142,  160,
      159,  217,  143,  158,  217,  247,  140,  137,  144,  141,
      157,   96,  142,  220,   95,  217,  143,  218,  219,  246,
      218,  217,  144,  218,  219,  246,  218,  220,  248,  244,
       94,  248,  247,  220,  375,   93,  375,  375,  375,  375,
      375,  133,   92,  245,  134,  156,  228,  375,  135,  228,
      375,  375,  153,  136,  137,  258,  258,  258,  255,  237,

      237,  237,  238,  151,  150,  238,  249,  232,  250,  149,
      232,  251,  148,  252,  147,  239,  262,  262,  262,  232,
      146,   61,  232,  375,  236,   82,   81,  236,  233,  233,
      233,   78,  114,  237,  237,  237,  240,  265,  267,  240,
      265,  267,  262,  262,  262,  113,  266,  266,  266,  241,
      141,  268,  141,  142,  112,  142,  105,  143,  248,  143,
      104,  248,  247,  144,  103,  144,  375,   96,  375,  375,
      375,  375,  375,  133,   95,   94,  134,  266,  266,  266,
      135,  281,   93,   92,  281,  136,  137,   82,   81,  271,
      258,  258,  258,   78,  267,  270,  249,  267,  250,   61,

      274,  232,  275,  375,  232,  278,  265,  268,  375,  265,
      262,  262,  262,  375,  375,  266,  266,  266,  286,  141,
      141,  286,  142,  142,  375,  375,  143,  143,  375,  375,
      375,  287,  144,  144,  375,  375,  133,  375,  375,  134,
      375,  285,  375,  135,  285,  300,  375,  286,  136,  137,
      286,  301,  375,  375,  301,  375,  375,  302,  375,  302,
      287,  375,  375,  375,  375,  133,  375,  375,  134,  375,
      290,  291,  135,  296,  375,  292,  296,  305,  137,  312,
      312,  312,  310,  310,  310,  301,  317,  313,  301,  317,
      314,  302,  375,  302,  143,  310,  310,  310,  375,  375,

      144,  312,  312,  312,  313,  375,  375,  313,  230,  313,
      375,  317,  314,  323,  317,  330,  324,  319,  375,  375,
      189,  375,  319,  189,  190,  176,  375,  177,  375,  375,
      375,  375,  375,  141,  375,  375,  142,   74,  375,  375,
      324,  375,  320,  375,  321,  375,  319,  325,  375,  326,
      375,  331,  375,  336,  375,  259,  337,   74,  259,  375,
      338,  375,  375,  333,  186,  334,  339,  186,  375,  375,
      375,  375,  375,  340,  340,  340,  141,  375,  141,  142,
       74,  142,   74,  324,  375,  324,  375,  375,  375,  319,
      375,  319,  375,  375,  375,  375,  375,  375,  375,  375,

      375,  375,  375,  336,  375,  259,  337,  350,  259,  375,
      338,  375,  375,  341,  375,  342,  339,  346,  375,  336,
      375,  347,  336,  282,  348,  354,  375,  259,  354,  355,
      259,  349,  339,  336,  375,  259,  337,  350,  259,  351,
      338,  375,  351,  282,  375,  375,  339,  375,  352,  352,
      352,  141,  375,  361,  141,  375,  361,  375,  375,  375,
      340,  340,  340,  141,  319,  141,  142,   74,  142,   74,
      324,  375,  324,  375,  347,  375,  319,  375,  319,  375,
      375,  375,  375,  375,  375,  141,  361,  375,  142,  361,
      369,  351,  143,  375,  351,  282,  375,  356,  144,  357,

      352,  352,  352,  375,  336,  375,  375,  336,  282,  375,
      375,  375,  375,  352,  352,  352,  363,  339,  375,  375,
      375,  259,  362,  259,  259,  282,  259,  354,  375,  259,
      354,  355,  259,  141,  375,  141,  142,   74,  142,   74,
      324,  375,  324,  375,  375,  375,  319,  141,  319,  141,
      142,   74,  142,   74,  324,  375,  324,  375,  375,  375,
      319,  375,  319,  375,  375,  375,  375,  375,  375,  375,
      375,  375,  365,  375,  375,  375,  375,  375,  364,   10,
       10,   10,   10,   10,   48,   48,  375,   48,   48,   60,
       60,   60,   60,   60,   72,  375,  375,  375,   72,  117,

      117,  375,  375,  117,   73,   73,  375,  375,   73,   74,
       74,  375,  375,   74,  168,  168,  375,  168,  178,  178,
      375,  375,  178,  188,  188,  375,  375,  188,  199,  199,
      375,  375,  199,  216,  216,  375,  216,  216,  218,  218,
      375,  218,  229,  229,  375,  375,  229,  234,  234,  375,
      234,  259,  259,  375,  259,  299,  299,  375,  375,  299,
      311,  311,  375,  311,  322,  322,  375,  375,  322,  329,
      329,  375,  375,  329,  332,  332,  375,  375,  332,  335,
      335,  375,  335,  335,  345,  345,  375,  345,  353,  353,
      375,  353,  353,  368,  368,  375,  375,  368,  371,  371,

      375,  371,    9,  375,  375,  375,  375,  375,  375,  375,
      375,  375,  375,  375,  375,  375,  375,  375,  375,  375,
      375,  375,  375,  375,  375,  375,  375,  375,  375,  375,
      375,  375,  375,  375,  375,  375,  375,  375,  375,  375,
      375,  375,  375,  375,  375,  375,  375,  375,  375,  375
    } ;

static yyconst short int yy_chk[1351] =
    {   0,
        0,    1,    1,    0,    1,  249,    1,    2,    2,  288,
        2,    0,    2,    0,    2,    2,    2,    2,    2,   20,
       20,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        4,   18,    2,    4,    2,    2,   18,   18,  249,    2,
       11,    5,    5,   11,    5,   11,    5,    2,    3,    3,
      288,    3,    6,    3,    4,    6,   64,    7,    7,   64,
        7,   22,    7,    4,  372,   39,    4,   39,   22,    5,
        4,    4,    3,    8,  272,    5,    8,   45,  371,   45,
        6,    3,    5,   25,    3,    7,    6,   25,    3,    3,
      107,    7,  107,    6,  250,   25,   54,   54,    7,   16,

       46,    8,   16,   46,  272,   46,   16,    8,   16,   16,
       16,   19,   16,  370,    8,   14,   19,   19,   14,  116,
       14,  116,   14,   14,   14,   14,   14,  250,   19,   14,
       14,   14,   14,   14,   14,   14,   14,   14,   38,   52,
       14,   38,   14,   14,   52,   52,   56,   14,   33,  122,
      122,  122,   33,   56,   32,   14,   17,   32,   17,  367,
       33,  273,   17,   17,   33,   34,   38,  359,   34,  358,
       34,   65,   38,   59,   65,   17,  345,   59,   32,   38,
       17,   17,   17,   26,  289,   59,   26,   32,   26,   82,
       32,  273,   82,   34,   32,   32,  344,   40,   44,   34,

       40,   44,   40,   53,  231,  231,   34,   26,   53,   53,
       62,  343,  149,   62,   62,  149,   26,  289,   63,   26,
       53,   63,   63,   26,   26,   40,   44,  124,  124,  124,
      328,   40,   44,   50,   74,  327,   50,   74,   40,   44,
       50,   74,   50,   50,   50,   66,   50,   74,   66,   67,
       72,  316,   67,   72,   66,   66,   66,   72,   67,   67,
       67,   68,   72,   72,   68,   69,   73,  315,   69,   73,
       68,   68,   68,  311,   69,   69,   69,   70,   73,  295,
       70,   71,   75,  295,   71,   75,   70,   70,   70,   75,
       71,   71,   71,   84,   75,   75,   84,   98,  308,   99,

      108,   98,   99,  108,   99,  108,  307,  117,  306,   98,
      117,  117,  304,   98,  153,  119,  303,  153,  119,  126,
      126,  126,  294,   75,  119,  119,  119,   99,  108,  128,
      128,  128,  293,   99,  108,  120,  280,   84,  120,  121,
       99,  108,  121,  279,  120,  120,  120,  261,  121,  121,
      121,  123,  284,  284,  123,  125,  133,  260,  125,  133,
      123,  123,  123,  259,  125,  125,  125,  127,  133,  133,
      127,  129,  194,  257,  129,  194,  127,  127,  127,  256,
      129,  129,  129,  130,  130,  130,  131,  254,  253,  131,
      132,  132,  132,  243,  235,  131,  131,  131,  134,  264,

      234,  134,  264,  135,  140,  134,  135,  140,  227,  226,
      134,  134,  135,  135,  135,  135,  136,  283,  137,  136,
      283,  137,  137,  136,  138,  139,  224,  138,  139,  136,
      137,  281,  141,  223,  281,  141,  138,  139,  218,  207,
      142,  206,  140,  142,  140,  141,  144,  142,  143,  144,
      144,  143,  246,  142,  136,  246,  136,  143,  143,  143,
      145,  201,  196,  145,  246,  152,  154,  145,  152,  154,
      154,  281,  145,  145,  152,  152,  152,  157,  193,  192,
      157,  169,  169,  169,  185,  184,  145,  170,  170,  170,
      157,  171,  168,  167,  171,  172,  174,  166,  172,  174,

      171,  171,  171,  171,  172,  172,  172,  172,  173,  174,
      188,  173,  189,  188,  188,  189,  189,  173,  173,  173,
      173,  173,  175,  164,  176,  175,  163,  176,  161,  175,
      160,  176,  159,  158,  174,  175,  174,  176,  177,  183,
      178,  177,  183,  178,  178,  177,  179,  156,  151,  179,
      179,  177,  178,  180,  150,  148,  180,  180,  179,  147,
      175,  176,  175,  146,  181,  180,  181,  181,  181,  181,
      182,  114,  113,  182,  182,  177,  181,  183,  186,  183,
      195,  186,  187,  195,  195,  187,  112,  186,  186,  186,
      111,  187,  187,  187,  191,  187,  110,  191,  198,  198,

      198,  191,  202,  109,  105,  202,  191,  191,  182,  199,
      182,  104,  199,  199,  204,  202,  103,  204,  199,  199,
      199,  203,  102,  205,  203,  191,  205,  204,  101,  100,
      203,  203,  203,   96,  213,  214,  205,  213,  214,   95,
       94,  217,  214,   93,  217,  217,  213,  213,  214,  215,
       92,   91,  215,  217,   90,  216,  215,  216,  216,  216,
      216,  219,  215,  219,  219,  219,  219,  216,  220,  214,
       89,  220,  220,  219,  221,   88,  222,  221,  221,  222,
      222,  225,   87,  215,  225,   85,  228,  229,  225,  228,
      229,  229,   83,  225,  225,  228,  228,  228,  225,  237,

      237,  237,  238,   81,   80,  238,  220,  232,  220,   79,
      232,  221,   78,  222,   77,  238,  232,  232,  232,  233,
       76,   60,  233,  233,  236,   58,   57,  236,  233,  233,
      233,   55,   43,  236,  236,  236,  240,  241,  242,  240,
      241,  242,  262,  262,  262,   42,  241,  241,  241,  240,
      244,  242,  245,  244,   41,  245,   37,  244,  248,  245,
       36,  248,  248,  244,   35,  245,  251,   31,  252,  251,
      251,  252,  252,  255,   30,   29,  255,  266,  266,  266,
      255,  258,   28,   27,  258,  255,  255,   24,   23,  245,
      258,  258,  258,   21,  267,  244,  248,  267,  248,   15,

      251,  263,  252,    9,  263,  255,  265,  267,    0,  265,
      263,  263,  263,    0,    0,  265,  265,  265,  269,  270,
      271,  269,  270,  271,    0,  274,  270,  271,  274,  274,
        0,  269,  270,  271,  275,    0,  278,  275,  275,  278,
        0,  285,    0,  278,  285,  285,    0,  286,  278,  278,
      286,  287,  290,    0,  287,  290,  290,  287,  291,  287,
      286,  291,  291,  299,    0,  292,  299,  299,  292,    0,
      274,  275,  292,  296,    0,  278,  296,  292,  292,  302,
      302,  302,  296,  296,  296,  301,  310,  305,  301,  310,
      305,  301,    0,  301,  305,  310,  310,  310,    0,    0,

      305,  312,  312,  312,  313,    0,    0,  313,  313,  314,
        0,  317,  314,  314,  317,  317,  314,  313,    0,    0,
      319,    0,  314,  319,  319,  305,  320,  305,  321,  320,
      320,  321,  321,  322,    0,  329,  322,  322,  329,  329,
      322,    0,  313,    0,  313,    0,  322,  314,    0,  314,
        0,  317,    0,  323,    0,  323,  323,  323,  323,    0,
      323,    0,    0,  320,  324,  321,  323,  324,  324,    0,
        0,    0,    0,  324,  324,  324,  325,    0,  326,  325,
      325,  326,  326,  325,  332,  326,    0,  332,  332,  325,
      333,  326,  331,  333,  333,  331,  331,  334,    0,    0,

      334,  334,    0,  335,    0,  335,  335,  335,  335,    0,
      335,    0,    0,  325,    0,  326,  335,  331,    0,  336,
        0,  331,  336,  336,  333,  339,    0,  339,  339,  339,
      339,  334,  336,  337,    0,  337,  337,  337,  337,  338,
      337,  346,  338,  338,  346,  346,  337,    0,  338,  338,
      338,  340,    0,  347,  340,  340,  347,  347,    0,    0,
      340,  340,  340,  341,  340,  342,  341,  341,  342,  342,
      341,    0,  342,    0,  346,    0,  341,  348,  342,  349,
      348,  348,  349,  349,    0,  350,  361,    0,  350,  361,
      361,  351,  350,    0,  351,  351,    0,  341,  350,  342,

      351,  351,  351,    0,  352,    0,  362,  352,  352,  362,
      362,    0,    0,  352,  352,  352,  349,  352,    0,    0,
        0,  353,  348,  353,  353,  353,  353,  354,    0,  354,
      354,  354,  354,  356,    0,  357,  356,  356,  357,  357,
      356,  363,  357,    0,  363,  363,  356,  364,  357,  365,
      364,  364,  365,  365,  364,  368,  365,    0,  368,  368,
      364,    0,  365,    0,    0,    0,    0,    0,    0,    0,
        0,    0,  357,    0,    0,    0,    0,    0,  356,  376,
      376,  376,  376,  376,  377,  377,    0,  377,  377,  378,
      378,  378,  378,  378,  379,    0,    0,    0,  379,  380,

      380,    0,    0,  380,  381,  381,    0,    0,  381,  382,
      382,    0,    0,  382,  383,  383,    0,  383,  384,  384,
        0,    0,  384,  385,  385,    0,    0,  385,  386,  386,
        0,    0,  386,  387,  387,    0,  387,  387,  388,  388,
        0,  388,  389,  389,    0,    0,  389,  390,  390,    0,
      390,  391,  391,    0,  391,  392,  392,    0,    0,  392,
      393,  393,    0,  393,  394,  394,    0,    0,  394,  395,
      395,    0,    0,  395,  396,  396,    0,    0,  396,  397,
      397,    0,  397,  397,  398,  398,    0,  398,  399,  399,
        0,  399,  399,  400,  400,    0,    0,  400,  401,  401,

        0,  401,  375,  375,  375,  375,  375,  375,  375,  375,
      375,  375,  375,  375,  375,  375,  375,  375,  375,  375,
      375,  375,  375,  375,  375,  375,  375,  375,  375,  375,
      375,  375,  375,  375,  375,  375,  375,  375,  375,  375,
      375,  375,  375,  375,  375,  375,  375,  375,  375,  375
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "cfg.l"
#define INITIAL 0
#line 2 "cfg.l"
/*
 * Cfg file reader, Greg Lee, 8/93.
 * Adapted from Adagio for KMidi 12/99.
 *	$Id$
 */
#include <ctype.h>
#include <stdlib.h>
#include <unistd.h>
#include <string.h>
#include "config.h"
#include "common.h"
#include "instrum.h"
#include "playmidi.h"
#include "readmidi.h"
#include "output.h"
#include "controls.h"
#include "tables.h"
#include "version.h"

#define YY_ALWAYS_INTERACTIVE 0
#define YY_NEVER_INTERACTIVE 1

#define YY_INPUT(buf,result,max_size) \
	 result = fread( buf, 1, max_size, yyin );


static int prescanning;
static char doing_drums = false;
static char doing_sf = false;
static int patchno = -1, i, j;
static char *patchname;
static char cfg_flag = 1;
static int tone_bank;
static void set_patchno(char *m);

static char *dirname = 0;
static char *sfname = 0;

static int current_toneset = 0;
static int current_drumset = 0;

static int cfg_condition = -1;

static ToneBank *bank=0;
static int banknum=0;
static int rcf_count=1;
static int font_type=FONT_NORMAL;


#define MAX_INCLUDE_DEPTH 40
static YY_BUFFER_STATE include_stack[MAX_INCLUDE_DEPTH];
static int include_stack_ptr = 0;

static void new_toneset(int n);
static void new_patch(const char *vname, int num);

#define YY_NO_UNPUT 1
#define P 1
#define K 2
#define S 3


/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		yy_current_buffer->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 70 "cfg.l"



	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
		yy_current_state += YY_AT_BOL();
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 376 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_current_state != 375 );
		yy_cp = yy_last_accepting_cpos;
		yy_current_state = yy_last_accepting_state;

yy_find_action:
		yy_act = yy_accept[yy_current_state];

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 72 "cfg.l"
;
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 73 "cfg.l"
;
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 75 "cfg.l"
{
	int i = 0;
	while (isspace(yytext[i])) i++;
	i += 2;
	cfg_condition = atoi(yytext+i);
}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 81 "cfg.l"
{
	cfg_condition = 0;
}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 84 "cfg.l"
{
	int sf_oldbank, sf_newbank = banknum;
	int i = 0, j;
	while (isspace(yytext[i])) i++;
	if (yytext[i+1] == 'f') i += 2;
	else i += 3;
	while (isspace(yytext[i])) i++;
	if (yytext[i] == '"') {
		i++;
		for (j = i; j < yyleng && yytext[j] != '"'; j++) ;
		j--;
	}
	else for (j = i; j < yyleng && !isspace(yytext[j]); j++) ;
	sfname = strncpy( (char *)malloc(j-i+1), yytext+i, j-i );
	sfname[j-i] = '\0';
	if (doing_drums) sf_newbank += 256;
	sf_oldbank = sf_newbank;
	if (j < yyleng) {
		while (j < yyleng && isspace(yytext[j])) j++;
		if (j < yyleng && isdigit(yytext[j])) sf_oldbank = atoi(yytext+j);
	}
	init_soundfont(sfname, sf_oldbank, sf_newbank, rcf_count);
}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 107 "cfg.l"
{
	int i = 0;
	while (isspace(yytext[i])) i++;
	if (yytext[i] == 'd') i += 3;
	else i += 9;
	while (isspace(yytext[i])) i++;
	dirname = strcpy( (char *)malloc(strlen(yytext+i)+1), yytext+i );
	add_to_pathlist(dirname, rcf_count);
	free(dirname);
}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 117 "cfg.l"
{
	char *fname;
	int i = 0;
	FILE *save_yyin;

	while (isspace(yytext[i])) i++;
	i += 6;
	while (isspace(yytext[i])) i++;

	 if (prescanning && cfg_condition >= 0 && cfg_condition < 30 &&
		rcf_count==1 && !cfg_names[cfg_condition])
	  {
	    cfg_names[cfg_condition] = (char *)safe_malloc(strlen(yytext+i)+1);
	    strcpy(cfg_names[cfg_condition], yytext+i);
	  }

    if (!prescanning && (cfg_condition < 0 || cfg_condition == cfg_select)) {


        if ( include_stack_ptr >= MAX_INCLUDE_DEPTH ) {
		ctl->cmsg(CMSG_ERROR, VERB_NORMAL,
		 "Probable source loop in configuration files");
		return (-1);
        }
        include_stack[include_stack_ptr++] =
                YY_CURRENT_BUFFER;

	fname = strcpy( (char *)malloc(strlen(yytext+i)+1), yytext+i );

	save_yyin = yyin;
	yyin = NULL;

	yyin = open_file(fname, 1, OF_VERBOSE, rcf_count);

	if (yyin == NULL) {
		ctl->cmsg(CMSG_ERROR, VERB_NORMAL,
		 "Source file %s not found\n", fname);
		include_stack_ptr--;
	}

	if (yyin == NULL) yyin = save_yyin;
	else {
            cfg_condition = -1;
	    rcf_count++;
            yy_switch_to_buffer(
                yy_create_buffer( yyin, YY_BUF_SIZE ) );
	}
    }
    cfg_condition = -1;
}  
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(P):
case YY_STATE_EOF(K):
case YY_STATE_EOF(S):
#line 168 "cfg.l"
{
        if ( --include_stack_ptr < 0 ) {
                yyterminate();
        }
        else {
		if (yyin) close_file(yyin);
                yy_delete_buffer( YY_CURRENT_BUFFER );
		rcf_count--;
                yy_switch_to_buffer(
                     include_stack[include_stack_ptr] );
        }
}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 181 "cfg.l"
{
	char *bank_name = NULL;
	int i = 0;
	while (isspace(yytext[i])) i++;
	i += 7;
	current_drumset = atoi(yytext+i);
	doing_drums = true;
	doing_sf = true;
	new_toneset(current_drumset);
	font_type=FONT_SBK;
    if (!bank->name) {
	while (isspace(yytext[i])) i++;
	while (isdigit(yytext[i])) i++;
	while (isspace(yytext[i])) i++;
	if (yytext[i+1] == 'f') i += 2; else i += 3;
	while (isspace(yytext[i])) i++;
	patchname = yytext + i;
	if (patchname[0] == '"') {
		bank_name = strncpy( (char *)malloc(strlen(patchname)-1), patchname + 1, strlen(patchname)-1 );
		bank_name[strlen(patchname)-2] = '\0';
	}
	else bank_name = strcpy( (char *)malloc(strlen(patchname)+1), patchname );
	bank->name = bank_name;
    }

}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 207 "cfg.l"
{
	int i = 0;
	while (isspace(yytext[i])) i++;
	i += 7;
	current_drumset = atoi(yytext+i);
	doing_drums = true;
	doing_sf = true;
	new_toneset(current_drumset);
	font_type=FONT_SBK;
}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 217 "cfg.l"
{
	char *bank_name = NULL;
	int i = 0;
	while (isspace(yytext[i])) i++;
	i += 7;
	current_drumset = atoi(yytext+i);
	doing_drums = true;
	doing_sf = false;
	new_toneset(current_drumset);
	font_type=FONT_NORMAL;
    if (!bank->name) {
	while (isspace(yytext[i])) i++;
	while (isdigit(yytext[i])) i++;
	while (isspace(yytext[i])) i++;
	patchname = yytext + i;
	if (patchname[0] == '"') {
		bank_name = strncpy( (char *)malloc(strlen(patchname)-1), patchname + 1, strlen(patchname)-1 );
		bank_name[strlen(patchname)-2] = '\0';
	}
	else bank_name = strcpy( (char *)malloc(strlen(patchname)+1), patchname );
	bank->name = bank_name;
    }
}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 240 "cfg.l"
{
	int i = 0;
	while (isspace(yytext[i])) i++;
	i += 7;
	current_drumset = atoi(yytext+i);
	doing_drums = true;
	doing_sf = false;
	new_toneset(current_drumset);
	font_type=FONT_NORMAL;
}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 250 "cfg.l"
{
	int i = 0;
	while (isspace(yytext[i])) i++;
	i += 4;
	current_toneset = atoi(yytext+i);
	doing_drums = false;
	doing_sf = true;
	new_toneset(current_toneset);
	font_type=FONT_SBK;
}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 260 "cfg.l"
{
	int i = 0;
	while (isspace(yytext[i])) i++;
	i += 4;
	current_toneset = atoi(yytext+i);
	doing_drums = false;
	doing_sf = false;
	new_toneset(current_toneset);
	font_type=FONT_NORMAL;
}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 270 "cfg.l"
{
	current_toneset = SFXBANK;
	doing_drums = false;
	doing_sf = false;
	new_toneset(current_toneset);
	font_type=FONT_NORMAL;
}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 277 "cfg.l"
{
	current_drumset = SFXDRUM1;
	doing_drums = true;
	doing_sf = false;
	new_toneset(current_toneset);
	font_type=FONT_NORMAL;
	bank->name = "drumsfx1";
}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 285 "cfg.l"
{
	current_drumset = SFXDRUM2;
	doing_drums = true;
	doing_sf = false;
	new_toneset(current_toneset);
	font_type=FONT_NORMAL;
	bank->name = "drumsfx2";
}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 294 "cfg.l"
{
	doing_drums = false;
}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 297 "cfg.l"
{
	doing_drums = true;
	current_drumset = current_toneset;
}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 302 "cfg.l"
{
	const char *gm_name = NULL;
	char *vc_name = NULL;
	patchno = atoi(yytext);
	tone_bank = 0;
	if (patchno >= 0) {
		i = 0;
		while (isspace(yytext[i])) i++;
		while (isdigit(yytext[i])) i++;
		if (yytext[i] == ',') {
			i++;
			tone_bank = atoi(yytext + i);
			while (isdigit(yytext[i])) i++;
		}
		else {
			if (doing_drums) tone_bank = current_drumset;
			else tone_bank = current_toneset;
		}
		new_toneset(tone_bank);

		while (isspace(yytext[i])) i++;
		if (!cfg_flag && yytext[i] == '=') i++;
		if ( (patchname = strrchr(yytext + i, '\\')) == NULL)
			patchname = yytext + i;
		else patchname++;
		if (patchname[0] == '"') {
			vc_name = strncpy( (char *)malloc(strlen(patchname)-1), patchname + 1, strlen(patchname)-1 );
			vc_name[strlen(patchname)-2] = '\0';
		}
		else vc_name = strcpy( (char *)malloc(strlen(patchname)+1), patchname );
		if (patchno < 128) gm_name = gm_voice[doing_drums? patchno+128 : patchno].vname;
		else {
		    ctl->cmsg(CMSG_ERROR, VERB_NORMAL, "Bad patch number %d in cfg file.", patchno);
		}
		if (gm_name == NULL) gm_name = (doing_drums)? "drum":"instr";

	        ctl->cmsg(CMSG_INFO, VERB_DEBUG, "config: voice %s[%d,%d] = patch %s",
			gm_name, patchno, tone_bank, vc_name);

		new_patch(vc_name, patchno);

	}
	BEGIN(P);
}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 347 "cfg.l"
{
	const char *gm_name = NULL;
	char *vc_name = NULL;
	int i;
	set_patchno(yytext);
	tone_bank = 0;
	if (patchno < 256) {
		i = 0;
		while (yytext[i] != '=' && yytext[i] != ',') i++;
		if (yytext[i] == ',') {
			i++;
			tone_bank = atoi(yytext + i);
		}
		else {
			if (doing_drums) tone_bank = current_drumset;
			else tone_bank = current_toneset;
		}

		while (yytext[i] != '=') i++;
		i++;
		while (isspace(yytext[i])) i++;
		if ( (patchname = strrchr(yytext + i, '\\')) == NULL)
			patchname = yytext + i;
		else patchname++;
		if (patchname[0] == '"') {
			vc_name = strncpy( (char *)malloc(strlen(patchname)-1), patchname + 1, strlen(patchname)-1 );
			vc_name[strlen(patchname)-2] = '\0';
		}
		else vc_name = strcpy( (char *)malloc(strlen(patchname)+1), patchname );
		gm_name = gm_voice[patchno].vname;
		if (gm_name == NULL) gm_name = (doing_drums)? "drum":"instr";

	        ctl->cmsg(CMSG_INFO, VERB_DEBUG, "config: voice %s[%d,%d] = patch %s",
			gm_name, patchno, tone_bank, vc_name);

	}
	else {
		ctl->cmsg(CMSG_ERROR, VERB_NORMAL, "Bad line \"%s ...\" in cfg file.", yytext);
	}
	new_patch(vc_name, patchno);
	
	BEGIN(P);
}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 391 "cfg.l"
{ if (prescanning) {
		i=0; while(isspace(yytext[i])) i++;
		j = atoi(yytext+i+2);
		if (j > 1 && j < MAX_VOICES) voices = j;
	} }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 396 "cfg.l"
{ if (prescanning) {
		i=0; while(isspace(yytext[i])) i++;
		j = atoi(yytext+i+2);
		if (j > 1 && j < MAX_AMPLIFICATION) amplification = j;
	} }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 401 "cfg.l"
{ if (prescanning) {
		i=0; while(isspace(yytext[i])) i++;
		j = atoi(yytext+i+2);
		if (j > 1 && j < MAX_CONTROL_RATIO) control_ratio = j;
	} }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 406 "cfg.l"
{ if (prescanning) {
		i=0; while(isspace(yytext[i])) i++;
		j = atoi(yytext+i+2);
		if (j < 100) j *= 1000;
		if (j > MIN_OUTPUT_RATE && j < MAX_OUTPUT_RATE) play_mode->rate = j;
	} }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 412 "cfg.l"
{ if (prescanning) {
		i=0; while(isspace(yytext[i])) i++;
		j = atoi(yytext+i+2);
		max_patch_memory = j * 1000000;
	} }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 417 "cfg.l"
{ if (prescanning) {
		i=0; while(isspace(yytext[i])) i++;
		j = atoi(yytext+i+2);
		if (j >= 0 && j <= 3) current_interpolation = j;
	} }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 422 "cfg.l"
{ if (prescanning) {
		i=0; while(isspace(yytext[i])) i++;
		j = atoi(yytext+i+2);
		if (j >= 0 && j <= 2) opt_expression_curve = j;
	} }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 427 "cfg.l"
{ if (prescanning) {
		i=0; while(isspace(yytext[i])) i++;
		j = atoi(yytext+i+2);
		if (j >= 0 && j <= 2) opt_volume_curve = j;
	} }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 433 "cfg.l"
{
	int i = 0;
	while (yytext[i] != '=') i++;
	bank->tone[patchno].amp = atoi(yytext+i+1);
	BEGIN(P);
}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 439 "cfg.l"
{
	int i = 0;
	while (yytext[i] != '=') i++;
	bank->tone[patchno].note = atoi(yytext+i+1);
	BEGIN(P);
}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 445 "cfg.l"
{
	int i = 0;
	while (yytext[i] != '=') i++;
	bank->tone[patchno].tuning = atoi(yytext+i+1);
	BEGIN(P);
}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 451 "cfg.l"
BEGIN(K);
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 452 "cfg.l"
BEGIN(S);
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 454 "cfg.l"
{
		  bank->tone[patchno].strip_loop=0;
	BEGIN(P);
}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 458 "cfg.l"
{
		  bank->tone[patchno].strip_tail=0;
	BEGIN(P);
}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 462 "cfg.l"
{
		  bank->tone[patchno].strip_envelope=0;
	BEGIN(P);
}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 466 "cfg.l"
{
		  bank->tone[patchno].strip_loop=1;
	BEGIN(P);
}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 470 "cfg.l"
{
		  bank->tone[patchno].strip_tail=1;
	BEGIN(P);
}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 474 "cfg.l"
{
		  bank->tone[patchno].strip_envelope=1;
	BEGIN(P);
}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 478 "cfg.l"
{
	set_patchno(yytext);
	if (patchno < 256) gm_voice[patchno].flags &= ~SOLO_MASK;
}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 482 "cfg.l"
{
	set_patchno(yytext);
	if (patchno < 256) gm_voice[patchno].flags |= SOLO_MASK;
}
	YY_BREAK
case 42:
#line 488 "cfg.l"
case 43:
YY_RULE_SETUP
#line 488 "cfg.l"
{
	patchno = -1;
	BEGIN(0);
}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 492 "cfg.l"
ECHO;
	YY_BREAK

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_last_accepting_cpos;
				yy_current_state = yy_last_accepting_state;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;
	yy_current_state += YY_AT_BOL();

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 376 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 376 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 375);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;

	yy_current_buffer->yy_at_bol = (c == '\n');

	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 492 "cfg.l"


static void new_toneset(int n)
{
	banknum=n;

	if (!doing_drums) {
	  if (!tonebank[n]) {
		tonebank[n]=(ToneBank *)safe_malloc(sizeof(ToneBank));
	      	memset(tonebank[n], 0, sizeof(ToneBank));
	  }
	  bank=tonebank[n];
	}
	else {
	  if (!drumset[n]) {
		drumset[n]=(ToneBank *)safe_malloc(sizeof(ToneBank));
	      	memset(drumset[n], 0, sizeof(ToneBank));
	  }
	  bank=drumset[n];
	}
}

static void new_patch(const char *vname, int num)
{
	if (bank->tone[num].name) return;
	bank->tone[num].name=vname;
	bank->tone[num].note=bank->tone[num].amp=bank->tone[num].pan=
	  bank->tone[num].strip_loop=bank->tone[num].strip_envelope=
	    bank->tone[num].sf_ix=
	    bank->tone[num].strip_tail=bank->tone[num].last_used=-1;
	bank->tone[num].font_type=font_type;
	bank->tone[num].tuning=0;
	bank->tone[num].layer=0;
}

static void set_patchno(char *m)
{
	int i,j,w,y;
	const char *vn;
	y = w = 0;
	while (isspace(m[w])) w++;
	for (i = 0; i < 256; i++) {
		vn = gm_voice[i].vname;
		if (vn == NULL) continue;
		for (j = 0; m[j+w] && vn[j+y] && m[j+w] == vn[j+y]; j++)
		    if (vn[j+y+1] && isspace(vn[j+y+1]) && m[j+w+1] && !isspace(m[j+w+1]) ) y++ ;
		if (!m[j+w] || m[j+w] == '=' || m[j+w] == ',' || m[j+w] == ':') break;
		if (!vn[j+y] && isspace(m[j+w])) break;
	}
	if (i < 256 && vn != NULL) patchno = i;
	else patchno = 256;
}


char *current_config_file = 0;

int read_config_file(const char *name, int prescan)
{
	int retvalue;
	prescanning = prescan;
	include_stack_ptr = 0;
	rcf_count = 1;

	if (prescanning) {
	   current_config_file = (char *)safe_malloc(strlen(name)+1);
	   strcpy(current_config_file, name);
	}

	yyin = open_file(name, 1, OF_VERBOSE, rcf_count);
	if (!yyin) return -1;

	current_toneset = current_drumset = 0;
	doing_drums = doing_sf = false;
	if (!(retvalue = yylex())) {
	   if (prescan) got_a_configuration = 1;
	   else got_a_configuration = 2;
	}
	close_file(yyin);
	return retvalue;
}
