#!/bin/sh
srcdir=$1
for header in common config controls ctl effects filter instrum mix \
              output playmidi readmidi resample sbk sflayer tables \
              version ; do
    if [ ! -h ${header}.h ]; then ln -s ${srcdir}/${header}.h . ; fi
done

for cfile in alsa_a arts_a b_out bag bsd20_a celeste_e chorus_e \
	     common controls cfg ctl dec_a dumb_c effects esd_a \
	     fffload filter gentxt getopt hpux_a hpux_d_a instrum \
	     linux_a linux_a2 mix nas_a ncurs_c output phaser_e \
	     playmidi raw_a readmidi readsbk resample resample_f \
	     resample_l reverb_e sbktext sf2cfg slang_c sndfont \
	     sun_a tables timidity wav2pat wave_a ; do
    if [ ! -h ${cfile}.c ]; then ln -s ${srcdir}/${cfile}.cpp ${cfile}.c ; fi
done

for lfile in cfg ; do
    if [ ! -h ${lfile}.l ]; then ln -s ${srcdir}/${lfile}.l . ; fi
done

for other in BITMAPS ; do
    if [ ! -h ${other} ]; then ln -s ${srcdir}/${other} . ; fi
done
